'use strict'
const test = require('node:test')
const assert = require('node:assert/strict')
const f = require('../src/lib/format')

test('time formatting', () => {
	assert.equal(f.formatTime(0), '0:00.0')
	assert.equal(f.formatTime(12.3), '0:12.3')
	assert.equal(f.formatTime(59.96), '1:00.0')
	assert.equal(f.formatTime(754.25), '12:34.3')
	assert.equal(f.formatTime(3600), '1:00:00.0')
	assert.equal(f.formatTime(3725.4), '1:02:05.4')
	assert.equal(f.formatTime(-0.2), '0:00.0')
	assert.equal(f.formatTime(75.6, { tenths: false }), '1:16')
})

test('unknown is "?", none is "-", never 0', () => {
	assert.equal(f.formatTime(undefined), f.UNKNOWN)
	assert.equal(f.formatTime(null), f.NONE)
	assert.equal(f.formatTime(NaN), f.UNKNOWN)
	assert.equal(f.formatTime('12'), f.UNKNOWN)
	assert.equal(f.formatSeconds(undefined), '?')
	assert.equal(f.formatSeconds(null), '-')
	assert.equal(f.formatSeconds(4.25), '4.3')
	assert.equal(f.formatBool(true), 'on')
	assert.equal(f.formatBool(false), 'off')
	assert.equal(f.formatBool(undefined), '?')
	assert.equal(f.formatBool(1), '?')
})

test('playlist item remaining', () => {
	assert.equal(f.itemRemaining({ time: 1.5, duration: 30 }), 28.5)
	assert.equal(f.itemRemaining({ time: 31, duration: 30 }), 0)
	assert.equal(f.itemRemaining(null), null)
	assert.equal(f.itemRemaining(undefined), undefined)
	assert.equal(f.itemRemaining({ time: 1 }), undefined)
})

test('clock forms for key faces: remaining rounds UP, elapsed DOWN', () => {
	assert.equal(f.formatClock(245.3, 'hms'), '0:04:05')
	assert.equal(f.formatClock(245.3, 'hms', { up: true }), '0:04:06')
	assert.equal(f.formatClock(4500, 'mmss'), '75:00')
	assert.equal(f.formatClock(65, 'mmss'), '01:05')
	assert.equal(f.formatClock(4.0000001, 's', { up: true }), '4', 'status rounding never adds a second')
	assert.equal(f.formatClock(0.05, 's', { up: true }), '1', 'the last second still shows')
	assert.equal(f.formatClock(0, 's', { up: true }), '0')
	assert.equal(f.formatClock(undefined, 'hms'), '?')
	assert.equal(f.formatClock(null, 'mmss'), '-')
	assert.equal(f.formatPercent(0.425), '43')
	assert.equal(f.formatPercent(1.2), '100')
	assert.equal(f.formatPercent(undefined), '?')
	assert.equal(f.progressBar(0.5, 4), '▰▰▱▱')
	assert.equal(f.progressBar(0, 3), '▱▱▱')
	assert.equal(f.progressBar(undefined), '?')
})
